### ISSUE TITLE
Unable to install using 'Semi-automatic Installation' instructions

### ISSUE THREAD

**Issue by soumyaa1804** [addshore/mediawiki-docker-dev#110]
I am trying to install MediaWiki for development purpose and used the Semi-automatic Installation instructions to do so. The command `INSTALL_DIR=~/src ./setup.sh` ran successfully inside the cloned repository. Then in the same directory, I ran `./create` which gave this error:
![image](https://user-images.githubusercontent.com/40785645/73592817-50811f00-4524-11ea-9a92-81639e60d788.png)

**Comment by sohomdatta1** [comment]
@soumyaa1804 I also ran into this issue, you need to create the local.env file mentioned in step 6, The automatic installer does everything correctly until step 5 and only creates a local.env file, but does not add any content to it causing the problem.

**Comment by Krinkle** [comment]
If I understand correctly, you did not encounter an error while running `./setup.sh`, but later when running `./create.sh`.

That is indeed as @sohomdatta1 expected because a step was skipped :)

As an example, see the CI steps which follow the same steps as well:
https://github.com/addshore/mediawiki-docker-dev/blob/196992b93d7aa74891dce5b5365312efe8f73ed7/.travis.yml#L14-L18
