### ISSUE TITLE
Port annoyances when mediawiki has to make requests to itself

### ISSUE THREAD

**Issue by addshore** [addshore/mediawiki-docker-dev#12]
So, while developing the FileImporter extension mediawiki makes a request to a user provided URL to get information from the mediawiki API.

So the setup is 2 sites, one called enwiki one called commons.
on commons you want to pass the URL to an images stored on enwiki in order to import it.

if the environment is setup to listen on the host machine on port 8080:

1. Request http://enwiki.web.mw.local:8080/wiki/File:Foo.jpg
2. Inside the docker network the host resolves to the webserver, but this isn't listening on port 8080 so the request fails.

1. Request http://enwiki.web.mw.local:80/wiki/File:Foo.jpg
2. Inside the docker network the host resolves to the webserver, this is listening on 80 and responds, however the API returns a result thinking it is serving data on 80 and thus things such as images reference port 80,
3. Mediawiki builds a response to show the user, but shows uses the image url using port 80 when 8080 is exposed on the host.
4. The html lands in the browser and can't load the image on port 80 as this isnt exposed by docker.

**Comment by Krinkle** [comment]
I think MediaWiki has the needed support to make this work, with separations like wgCanonicalServer and wgInternalServer. Although I guess that doesn't matter here. The urls MediaWiki makes itself aren't the issue. The urls given externally are the issue. Once in PHP-land, LocalSettings is responsible for mapping the different hostnames to a wiki configuration.

The main problem seems to be that it is expected that the internal and external host names are different. That way the internal network can use the internal hostname and port, and if given an external hostname by an end-user, it is forced to try the external host network instead (thus working, given that such url will also contains the external port).

While it is somewhat inefficient to via the external route, that is the canonical meaning of the url given by the user. And that should work.

Alternatively, if you want to keep it internal, you can try to shadow the external hostname *and* the external port within the docker network. The problem seems to be that right now the docker network shadows the external hostname but not the external port.

Making the external ports work is tricky, given there is probably not a 1:1 mapping (e.g. different web services and different mediawiki/php versions will all listen internally on port 80). If you want to go the route of external urls working within the internal network, we'll need to give them the same internal port as externally. I suppose there isn't any harm in making the internal ports the same as the external ones? (As long as they are still configurable and not hardcoded).

**Comment by addshore** [comment]
I did have a poke around with various mediawiki settings but couldn't make everything line up.
I'll probably revisit this at some stage.

**Comment by kostajh** [comment]
#70 has some related pain points.

**Comment by addshore** [comment]
Solved in https://github.com/addshore/mediawiki-docker-dev/pull/113#issuecomment-595747674
