### ISSUE TITLE
./addhost: line 18: /etc/hosts: Permission denied

### ISSUE THREAD

**Issue by legoktm** [addshore/mediawiki-docker-dev#13]
I have a bunch of:
```
Adding services to hosts file
./addhost: line 17: /etc/hosts: Permission denied
./addhost: line 18: /etc/hosts: Permission denied
./addhost: line 17: /etc/hosts: Permission denied
./addhost: line 18: /etc/hosts: Permission denied
./addhost: line 17: /etc/hosts: Permission denied
./addhost: line 18: /etc/hosts: Permission denied
```

I didn't run ./up as root - was I supposed to? http://localhost:8080 gives me a nginx 503.

**Comment by Krinkle** [comment]
I got the same issue. Running the top-level `up` command as root seems wrong. But in that case, the internal script editing `/etc/hosts` has to be changed to use `sudo` so that it will try to ask the user for permission instead of hard-failing.

Alternatively, we can make it so that it checks if the file contains the entries already so that users can also choose to add them manually or (after we switch to using wmftest.net) to also have the option of skipping it entirely if not caring about the offline use case when first using `mediawiki-docker-dev`. That quick-start ability would certainly help this method catch on, I think :)

Workaround:
* `Use wmftest.net` - https://github.com/Krinkle/mediawiki-docker-dev/commit/a606ef528ae7bf8f2a3bc7d0ecd3595c71a6807d
* `Disable addhost` - https://github.com/Krinkle/mediawiki-docker-dev/commit/cee22ae25b3a675dd4bd94487b054c478a4b01cc

**Comment by addshore** [comment]
So wmftest.net is now used as of #14, which means when connected to the internet we dont need the addhost script.

However it would make sense to continue allowing use of this while offline, so perhaps we can just make the add host command totally separate to up & down?

**Comment by Krinkle** [comment]
@addshore Yeah, that sounds good. Let's make it a separate step. One that can be optionally run.

Also, it'd be good to improve the logic to look at the existing content and only append if the entry isn't already there. And perhaps to fallback to echoing instructions to the terminal of what the user should copy/paste into it.
