### ISSUE TITLE
Mediawiki Seems Slow

### ISSUE THREAD

**Issue by tarrow** [addshore/mediawiki-docker-dev#57]
We on the exp team are all finding that it is slow to load pages.

I think @addshore said something about turning a debug off somewhere. Is that documented anyway?

**Comment by addshore** [comment]
Debugging is always enabled

https://github.com/addshore/mediawiki-docker-dev/blob/master/docker-compose.yml#L56-L60

You can just turn it off using the ENV vars provided by the webdevops image. But turning it on and off would require throwing that container away & creating a new one (which isn't necessarily a bad thing).

We should set it up so that debugging is on only when specific url params or cli env vars are available?
Or we could actually have  containers, 1 debug and 1 not, but that seems a bit wasteful..

**Comment by tarrow** [comment]
I'm not sure (right now) that this is the cause of my slowness.

Experimenting with XDEBUG_REMOTE_AUTOSTART=0 rather than 1 doesn't change the load speed. it still takes ~5.5 seconds to load an empty L1.

What does cut my load time to very short (<200ms) is deleting the cooking `cpPosIndex`. Looks like there is a mobile ticket about this: https://phabricator.wikimedia.org/T190082

Not sure if it related.. The cookie is set each time you load the page so it has to be repeatedly cleared.

**Comment by addshore** [comment]
Nothing to do with xdebug...

![image](https://user-images.githubusercontent.com/3308769/41365329-05807a02-6f31-11e8-82d0-21d8223ab197.png)

**Comment by addshore** [comment]
https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/440262/

Also created https://phabricator.wikimedia.org/T197206 on phab for searchability.

Just +2ed the patch, a pull of core should speed things up for everyone...
