### ISSUE TITLE
Maintenance scripts should not require --wiki default by default

### ISSUE THREAD

**Issue by nyurik** [addshore/mediawiki-docker-dev#63]
Currently, all maintenance scripts fail unless `--wiki default` is specified.  I think this shouldn't be required. I wasn't even aware of `default` (i thought it was `wiki`). Thx!

**Comment by Krinkle** [comment]
I've added the following to LocalSettings.php as one of the first statements:

```php
if ( PHP_SAPI === 'cli' && !defined( 'MW_DB' ) ) {
	define( 'MW_DB', 'default' );
}
```

Perhaps this is worth upstreaming? It effectively makes `--wiki` optional, by letting `--wiki=default` be the default.

The main reason I added it for myself is because `phpunit.php` is also technically a maintenance script, where I tend to forget it most often.

**Comment by nyurik** [comment]
@Krinkle thx, submitted a PR ^

**Comment by addshore** [comment]
Done!
