### ISSUE TITLE
Provide an option to test against sqlite

### ISSUE THREAD

**Issue by brightbyte** [addshore/mediawiki-docker-dev#87]
Some times, a patch breaks sqlite, so jenkins refuses to merge it. Then we have to debug the sqlite behavior. It would be very nice if mediawiki-docker-dev provided a way to do that. As things are now, it's back to setting up MediaWiki locally, just to test a single patch.

**Comment by Krinkle** [comment]
We currently allow switching between PHP versions quite smoothly. You update the `env` file, and let docker-compose swap the server out. It can literally take mere seconds. This is imho more sustainable long-term then trying to support multiple separate running versions (as Vagrant did).

We might be able to do the same for database backends. Although it'll be a bit more difficult to manage. For one, we'll probably need to expose the relevant ENV variable to the web server so that the built-in LocalSettings.php file can vary by it for DB-related settings.

Unlike for PHP versions though, it does mean database won't preserve. By itself that could be fine (you'll just have different wikis and can switch between them). Except that we also have other stateful things besides the database, such as images. That might be a problem. In that case, we may need to require a full destroy/create cycle, which makes it less attractive to switch in the way I propose here. Because you'd be forced to destroy the database you have, even though technically it wouldn't need to.

If we don't like that, then we might want to instead do this as part of the proposed mdd-cli (https://github.com/addshore/mediawiki-docker-dev/issues/84). That could have a specific command for switching databases that could decide to destroy the server but not the database image (just keep it detached for later re-use). That command could then also do smart things like vary the image-upload mount by db-type so that you don't have to destroy it.

Thoughts?

**Comment by addshore** [comment]
sqlite is partially supported in https://www.mediawiki.org/wiki/Cli now (though with some open bugs still)
